//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GU_DATA.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class gd_accident
    {
        public string code { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<decimal> lon { get; set; }
        public Nullable<decimal> lat { get; set; }
        public string locate { get; set; }
        public string level { get; set; }
        public string demage { get; set; }
        public string ge_charact { get; set; }
    }
}
