//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GU_DATA.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class gd_type
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string main_charact { get; set; }
        public string reason { get; set; }
        public string demange_charcat { get; set; }
    }
}
