//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GU_DATA.Entitys
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Text.RegularExpressions;

    public partial class gd_user
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "用户ID")]
        public int UID { get; set; }

        [Display(Name = "用户名")]
        [Required(ErrorMessage = "用户名不能为空")]
        [StringLength(13, MinimumLength = 2, ErrorMessage = "用户名应该为2-13位")]
        public string Name { get; set; }


        [Display(Name = "密码")]
        [Required(ErrorMessage = "密码不能为空")]
        [StringLength(13, MinimumLength = 7, ErrorMessage = "密码名应该为7-13位")]
        public string Password { get; set; }

       [Display(Name = "账号创建日期")]
        public Nullable<System.DateTime> CreatDay { get; set; }
        [Display(Name = "用户常用IP")]
        public string IP { get; set; }

        [Display(Name = "用户IP地址")]
        public string Ip_address { get; set; }



        [Display(Name = "地址")]
        [Required(ErrorMessage = "地址不能为空")]
        public string Address { get; set; }


        [Display(Name ="用户类型")]
        public string type { get; set; }

        [Display(Name = "确认密码")]
        [Required(ErrorMessage = "确认密码不能为空")]
        [StringLength(13, MinimumLength = 7, ErrorMessage = "确认密码名应该为7-13位")]
        public string ConfirmPassword { get; set; }




        [Display(Name = "真实姓名")]
        [Required(ErrorMessage = "真实姓名为必填项")]
        [RegularExpression(@"^[\u4e00-\u9fa5]+$", ErrorMessage = "真实姓名请输入中文")]
        public string ID_Name { get; set; }





        [Display(Name = "身份证号码")]
        [Required(ErrorMessage = "身份证号码为必填项")]
        [StringLength(18, MinimumLength = 18, ErrorMessage = "身份证为18位")]
        [RegularExpression(@"^\d{18}$", ErrorMessage = "身份证号码格式错误")]
        public string ID_Number { get; set; }



        [Display(Name = "电话号码")]
        [StringLength(11, MinimumLength = 7, ErrorMessage = "电话号码应为7-11位")]
        [RegularExpression(@"^((\+)?86|((\+)?86)?)0?1[3458]\d{9}$", ErrorMessage = "电话号码格式错误")]
        public string Phone { get; set; }




        [Display(Name = "邮箱")]
        [RegularExpression(@"^[^@]([a-zA-Z_0-9.])+@([a-zA-Z_0-9.])+[^@]$", ErrorMessage = "邮箱格式错误")]
        public string Email { get; set; }

        [Display(Name = "用户修改次数")]
        public int Change_times { get; set; }

    }
}
