//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GU_DATA.Entitys
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDDBEntities : DbContext
    {
        public GDDBEntities()
            : base("name=GDDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gd_accident> gd_accident { get; set; }
        public virtual DbSet<gd_loss> gd_loss { get; set; }
        public virtual DbSet<gd_type> gd_type { get; set; }
        public virtual DbSet<gd_user> gd_user { get; set; }
    }
}
